line-length = 120

[lint]
# Never enforce `E501` (line length violations).
# ignore = ["C901", "E501", "E741", "F402", "F823",]
# select = ["C", "E", "F", "I", "W"]
select = ["ALL"]
ignore = [
    "ANN002",
    "ANN003",
    "ANN401",
    "B008",
    "B028",
    "C901",
    "COM812",
    "COM819",
    "D100",
    "D101",
    "D102",
    "D103",
    "D105",
    "D107",
    "D203",
    "D205",
    "D206",
    "D213",
    "D300",
    "D415",
    "E111",
    "E114",
    "E117",
    "EM101",
    "EM102",
    "ERA001",
    "FBT001",
    "FBT002",
    "G004",
    "N806",
    "N812",
    "PLR0913",
    "PLR2004",
    "PTH",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "SLF001",
    "S603",
    "S607",
    "T201",
    "TD003",
    "TD002",
    "TRY002",
    "TRY003",
    "TRY201",
    "W191",
    "ANN204",
]


[lint.pydocstyle]
# Enforce Google-style docstrings
convention = "google"

# Ignore import violations in all `__init__.py` files.
[lint.per-file-ignores]
"__init__.py" = ["F401", "D104"]
"setup.py" = ["D100"]

[lint.extend-per-file-ignores]
"tests/**/*.py" = [
    # at least this three should be fine in tests:
    "ANN201",
    "D100",
    "D103",
    "S101",   # asserts allowed in tests...
    "ARG",    # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT",    # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    # The below are debateable
    "PLR2004", # Magic value used in comparison, ...
    "S311",    # Standard pseudo-random generators are not suitable for cryptographic purposes
]

"*.ipynb" = [
    "T201",   # `print` found
    "I001",   # Import block is un-sorted or un-formatted
    "ERA001", # Found commented-out code
    "F401",   # imported but unused
]

[lint.isort]
split-on-trailing-comma = false

[format]
skip-magic-trailing-comma = true
docstring-code-format = true
