_target_: codecarbon.EmissionsTracker
project_name: "imagine-hackathon-2026"
experiment_name: ${experiment_name}_${now:%Y-%m-%d}_${now:%H-%M-%S}
measure_power_secs: 10
save_to_file: True
save_to_api: True
api_call_interval: 6  # Will log to the API every 6 * 10 = 60 seconds
log_level: "WARNING"
output_dir: ${paths.codecarbon_dir}${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/
tracking_mode: "process"
gpu_ids: "0"  # Single-GPU tracking
