# @package _global_

# example hyperparameter optimization of some experiment with basic Hydra:
# uv run src/train.py hparams_search=basic experiment=example

hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached

  sweeper:
    params:
      module.optimizer.lr: range(0.01, 0.02, 0.005)
      datamodule.batch_size: choice(64, 128, 256)

tags: ["hyperparam", "train"]